// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs markdown-viewer`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "edit-markdown-table",
    "icon": "📋",
    "name": {
      "en": "Edit Markdown Table",
      "ja": "Markdown表エディタ",
      "zh": "编辑 Markdown 表格",
      "de": "Markdown-Tabelle bearbeiten",
      "es": "Editar tabla Markdown"
    },
    "desc": {
      "en": "Edit a table in a grid — the Markdown syntax stays perfectly aligned.",
      "ja": "グリッドで表を編集。Markdown記法の桁揃えは自動で維持。",
      "zh": "在网格中编辑表格，Markdown 语法始终保持对齐。",
      "de": "Bearbeite eine Tabelle im Raster — die Markdown-Syntax bleibt exakt ausgerichtet.",
      "es": "Edita una tabla en una cuadrícula: la sintaxis Markdown se mantiene perfectamente alineada."
    }
  },
  {
    "slug": "eml-viewer",
    "icon": "📧",
    "name": {
      "en": "EML Viewer",
      "ja": "EML ビューア",
      "zh": "EML 查看器",
      "de": "EML-Viewer",
      "es": "Visor de EML"
    },
    "desc": {
      "en": "Open a saved .eml email and read it in your browser.",
      "ja": ".eml メールファイルをブラウザで開いて読みます。",
      "zh": "在浏览器中打开并阅读 .eml 邮件文件。",
      "de": "Öffne eine gespeicherte .eml-E-Mail und lies sie im Browser.",
      "es": "Abre un correo .eml guardado y léelo en tu navegador."
    }
  },
  {
    "slug": "csv-viewer",
    "icon": "📊",
    "name": {
      "en": "CSV Viewer",
      "ja": "CSV ビューア",
      "zh": "CSV 查看器",
      "de": "CSV-Viewer",
      "es": "Visor de CSV"
    },
    "desc": {
      "en": "Open and read CSV files right in your browser.",
      "ja": "CSV ファイルをブラウザで開いて表示します。",
      "zh": "在浏览器里打开并查看 CSV 文件。",
      "de": "CSV-Dateien direkt im Browser öffnen und ansehen.",
      "es": "Abre y consulta archivos CSV en tu navegador."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'markdown-viewer';
